SELECT * FROM customers
--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, sum(purchase_amount) as revenue
FROM customers
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied = 'Yes' and purchase_amount > (SELECT AVG(purchase_amount) FROM customers)

-- Q3. Which are the top 5 products with the highest average review rating?

select top 5 item_purchased , round(avg(review_rating), 2) as avg_rating
from customers
group by item_purchased
order by avg_rating DESC

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, avg(purchase_amount) as avg_purchase_amount
from customers
where shipping_type in ('Express', 'Standard')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
COUNT(*) as total_customers,
avg(purchase_amount) as avg_spend, 
sum(purchase_amount) as total_revenue
from customers
group by subscription_status
order by total_revenue desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT top 5 item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC



--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as (
select 
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segement
from customers )
select customer_segement, count(*) as total_customer
from customer_type
group by customer_segement
order by total_customer desc;

--Q8. What are the top 3 most purchased products within each category? 
with total_ as (
select category, item_purchased,
count(customer_id) as total_customers
from customers
group by  category, item_purchased
),
rankk as (
select category, item_purchased, 
DENSE_RANK() OVER ( partition by category order by total_customers desc) as ranking
from total_
)
select category, item_purchased, ranking
from rankk
where ranking <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as repeat_customers
from customers
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 

select age_group, sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc;